apiVersion: v1
kind: ConfigMap
metadata:
  name: alquiler-config
data:
  HTTP_PORT: "8080"
  HTTP_ROOT_PATH: "/api"
  DB_URL: "postgresql://postgres-0.postgres:5432/alquiler_db"
  VEHICLE_SERVICE_URL: "http://vehicle-service:8080"
  CUSTOMER_SERVICE_URL: "http://customer-service:8080"
  CUSTOMER_BACKUP_SERVICE_URL: "http://customer-backup-service:8080"