apiVersion: apps/v1
kind: Deployment
metadata:
  name: alquiler-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alquiler-service
  template:
    metadata:
      labels:
        app: alquiler-service
    spec:
      containers:
        - name: alquiler-service
          image: alquiler-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: alquiler-config
            - secretRef:
                name: alquiler-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi                