apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rrhh
  name: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: anovoa1975/ms-jobs-service-cur-000512:1.0.0
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: job-service-config
            - secretRef:
                name: job-service-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi