server:
  port: 8084

spring:
  application:
    name: stock-service

  ###############################################
  # PostgreSQL (R2DBC - Reactive)
  ###############################################
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/stock_db
    username: admin
    password: 123456

  sql:
    init:
      mode: never

resilience4j:

  circuitbreaker:
    instances:
      providerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  retry:
    instances:
      providerService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError
        ignore-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.web.reactive.function.client.WebClientRequestException
  timelimiter:
    instances:
      providerService:
        timeout-duration: 1s

logging:
  level:
    org.springframework.r2dbc: DEBUG

service:
  providers:
    url: http://${SERVICE_PROVIDERS:localhost}:8083/api/v1/providers
